### PR TITLE
changed scope of d4 var to work with how browserify compiles

### PR DESCRIPTION
**Pull request by LomaxRx**

### CODE REVIEW

**Comment by heavysixer** [comment]
Did you manually change the references to d4 in the compiled file? Because if so that won't work with the way the lib is compiled from parts.

**Comment by LomaxRx** [comment]
no, i only changed the base.js file and compiled with grunt

**Comment by heavysixer** [comment]
Ok the compiled file looked a bit odd. Let me test your branch locally but if everything works i'll make a new release. Thanks!

**Comment by heavysixer** [comment]
One final question, is there a way to give a minimal browserify test for this? How did you confirm this worked?

**Comment by LomaxRx** [comment]
good question. I found this tool [browserify-test](https://github.com/alekseykulikov/browserify-test) and ran this test which passed:

```javascript
var expect = require( 'chai' ).expect;

describe('browserify test', function() {
  it('browserify should compile d4', function() {
       var d4 = require( '../lib/d4.js' );
      expect(d4).to.not.be.an('undefined');
  });
});
```

let me know if that works.

**Comment by heavysixer** [comment]
Awesome, can you integrate that with the existing test suite and append the PR you sent me? 

Thanks again for your hard work!

Best Regards,
Mark

**Comment by LomaxRx** [comment]
ok. no problem. I need to add grunt-browserify and a new task to run during `grunt test`. is that fine with you?

**Comment by heavysixer** [comment]
Perfect, I’ll confirm it works for me and then merge.

**Pull request merged**
